// examples/basic-server-react/src/mcp-app.tsx
/**
 * @file App that demonstrates a few features using MCP Apps SDK + React.
 */
import type { App, McpUiHostContext } from "@modelcontextprotocol/ext-apps";
import { useApp } from "@modelcontextprotocol/ext-apps/react";
import type { CallToolResult } from "@modelcontextprotocol/server";
import { StrictMode, useCallback, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import styles from "./mcp-app.module.css";


function extractTime(callToolResult: CallToolResult): string {
  const { text } = callToolResult.content?.find((c) => c.type === "text")!;
  return text;
}


function GetTimeApp() {
  const [toolResult, setToolResult] = useState<CallToolResult | null>(null);
  const [hostContext, setHostContext] = useState<McpUiHostContext | undefined>();

  // `useApp` (1) creates an `App` instance, (2) calls `onAppCreated` to
  // register handlers, and (3) calls `connect()` on the `App` instance.
  const { app, error } = useApp({
    appInfo: { name: "Get Time App", version: "1.0.0" },
    capabilities: {},
    onAppCreated: (app) => {
      app.onteardown = async () => {
        console.info("App is being torn down");
        return {};
      };
      app.ontoolinput = async (input) => {
        console.info("Received tool call input:", input);
      };

      app.ontoolresult = async (result) => {
        console.info("Received tool call result:", result);
        setToolResult(result);
      };

      app.ontoolcancelled = (params) => {
        console.info("Tool call cancelled:", params.reason);
      };

      app.onerror = console.error;

      app.onhostcontextchanged = (params) => {
        setHostContext((prev) => ({ ...prev, ...params }));
      };
    },
  });

  useEffect(() => {
    if (app) {
      setHostContext(app.getHostContext());
    }
  }, [app]);

  if (error) return <div><strong>ERROR:</strong> {error.message}</div>;
  if (!app) return <div>Connecting...</div>;

  return <GetTimeAppInner app={app} toolResult={toolResult} hostContext={hostContext} />;
}


interface GetTimeAppInnerProps {
  app: App;
  toolResult: CallToolResult | null;
  hostContext?: McpUiHostContext;
}
function GetTimeAppInner({ app, toolResult, hostContext }: GetTimeAppInnerProps) {
  const [serverTime, setServerTime] = useState("Loading...");
  const [messageText, setMessageText] = useState("This is message text.");
  const [logText, setLogText] = useState("This is log text.");
  const [linkUrl, setLinkUrl] = useState("https://modelcontextprotocol.io/");

  useEffect(() => {
    if (toolResult) {
      setServerTime(extractTime(toolResult));
    }
  }, [toolResult]);

  const handleGetTime = useCallback(async () => {
    try {
      console.info("Calling get-time tool...");
      const result = await app.callServerTool({ name: "get-time", arguments: {} });
      console.info("get-time result:", result);
      setServerTime(extractTime(result));
    } catch (e) {
      console.error(e);
      setServerTime("[ERROR]");
    }
  }, [app]);

  const handleSendMessage = useCallback(async () => {
    const signal = AbortSignal.timeout(5000);
    try {
      console.info("Sending message text to Host:", messageText);
      const { isError } = await app.sendMessage(
        { role: "user", content: [{ type: "text", text: messageText }] },
        { signal },
      );
      console.info("Message", isError ? "rejected" : "accepted");
    } catch (e) {
      console.error("Message send error:", signal.aborted ? "timed out" : e);
    }
  }, [app, messageText]);

  const handleSendLog = useCallback(async () => {
    console.info("Sending log text to Host:", logText);
    await app.sendLog({ level: "info", data: logText });
  }, [app, logText]);

  const handleOpenLink = useCallback(async () => {
    console.info("Sending open link request to Host:", linkUrl);
    const { isError } = await app.openLink({ url: linkUrl });
    console.info("Open link request", isError ? "rejected" : "accepted");
  }, [app, linkUrl]);

  return (
    <main
      className={styles.main}
      style={{
        paddingTop: hostContext?.safeAreaInsets?.top,
        paddingRight: hostContext?.safeAreaInsets?.right,
        paddingBottom: hostContext?.safeAreaInsets?.bottom,
        paddingLeft: hostContext?.safeAreaInsets?.left,
      }}
    >
      <p className={styles.notice}>Watch activity in the DevTools console!</p>

      <div className={styles.action}>
        <p>
          <strong>Server Time:</strong> <code className={styles.serverTime}>{serverTime}</code>
        </p>
        <button onClick={handleGetTime}>Get Server Time</button>
      </div>

      <div className={styles.action}>
        <textarea value={messageText} onChange={(e) => setMessageText(e.target.value)} />
        <button onClick={handleSendMessage}>Send Message</button>
      </div>

      <div className={styles.action}>
        <input type="text" value={logText} onChange={(e) => setLogText(e.target.value)} />
        <button onClick={handleSendLog}>Send Log</button>
      </div>

      <div className={styles.action}>
        <input type="url" value={linkUrl} onChange={(e) => setLinkUrl(e.target.value)} />
        <button onClick={handleOpenLink}>Open Link</button>
      </div>
    </main>
  );
}


createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <GetTimeApp />
  </StrictMode>,
);

// examples/basic-server-angular/src/mcp-app.ts
/**
 * @file App that demonstrates a few features using MCP Apps SDK + Angular.
 */
import { ChangeDetectionStrategy, Component, DestroyRef, inject, model, provideZonelessChangeDetection, signal } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { bootstrapApplication } from "@angular/platform-browser";
import { App, PostMessageTransport, type McpUiHostContext } from "@modelcontextprotocol/ext-apps";
import type { CallToolResult } from "@modelcontextprotocol/sdk/types.js";

function extractTime(callToolResult: CallToolResult): string {
  const { text } = callToolResult.content?.find((c) => c.type === "text")!;
  return text;
}

@Component({
  selector: "app-root",
  imports: [FormsModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  styleUrl: "./mcp-app.css",
  template: `
    @if (error()) {
      <div><strong>ERROR:</strong> {{ error() }}</div>
    }
    @if (!app() && !error()) {
      <div>Connecting...</div>
    }
    
    @if (app() && !error()) {
      <main 
        class="main"
        [style.padding-top.px]="hostContext()?.safeAreaInsets?.top"
        [style.padding-right.px]="hostContext()?.safeAreaInsets?.right"
        [style.padding-bottom.px]="hostContext()?.safeAreaInsets?.bottom"
        [style.padding-left.px]="hostContext()?.safeAreaInsets?.left"
      >
        <p class="notice">Watch activity in the DevTools console!</p>

        <div class="action">
          <p>
            <strong>Server Time:</strong> <code class="serverTime">{{ serverTime() }}</code>
          </p>
          <button (click)="handleGetTime()">Get Server Time</button>
        </div>

        <div class="action">
          <textarea [(ngModel)]="messageText"></textarea>
          <button (click)="handleSendMessage()">Send Message</button>
        </div>

        <div class="action">
          <input type="text" [(ngModel)]="logText" />
          <button (click)="handleSendLog()">Send Log</button>
        </div>

        <div class="action">
          <input type="url" [(ngModel)]="linkUrl" />
          <button (click)="handleOpenLink()">Open Link</button>
        </div>
      </main>
    }
  `,
})
export class GetTimeAppComponent {
  private destroyRef = inject(DestroyRef);

  protected readonly app = signal<App | null>(null);
  protected readonly error = signal<string | null>(null);
  protected readonly hostContext = signal<McpUiHostContext | undefined>(undefined);
  protected readonly serverTime = signal("Loading...");
  
  messageText = model("This is message text.");
  logText = model("This is log text.");
  linkUrl = model("https://modelcontextprotocol.io/");

  constructor() {
    this.initializeApp();

    this.destroyRef.onDestroy(async () => {
      const appInstance = this.app();
      if (appInstance) {
        await appInstance.close();
      }
    });
  }

  private async initializeApp(): Promise<void> {
    try {
      const appInstance = new App({
        name: "Get Time App",
        version: "1.0.0",
      });

      appInstance.onteardown = async () => {
        console.info("App is being torn down");
        return {};
      };

      appInstance.ontoolinput = async (input) => {
        console.info("Received tool call input:", input);
      };

      appInstance.ontoolresult = async (result) => {
        console.info("Received tool call result:", result);
        this.serverTime.set(extractTime(result));
      };

      appInstance.ontoolcancelled = (params) => {
        console.info("Tool call cancelled:", params.reason);
      };

      appInstance.onerror = console.error;

      appInstance.onhostcontextchanged = (params) => {
        this.hostContext.update(current => ({ ...current, ...params }));
      };

      const transport = new PostMessageTransport(window.parent, window.parent);
      await appInstance.connect(transport);

      this.hostContext.set(appInstance.getHostContext());
      this.app.set(appInstance);
    } catch (e) {
      this.error.set(e instanceof Error ? e.message : String(e));
      console.error(e);
    }
  }

  async handleGetTime(): Promise<void> {
    const appInstance = this.app();
    if (!appInstance) return;

    try {
      console.info("Calling get-time tool...");
      const result = await appInstance.callServerTool({ name: "get-time", arguments: {} });
      console.info("get-time result:", result);
      this.serverTime.set(extractTime(result));
    } catch (e) {
      console.error(e);
      this.serverTime.set("[ERROR]");
    }
  }

  async handleSendMessage(): Promise<void> {
    const appInstance = this.app();
    if (!appInstance) return;

    const signal = AbortSignal.timeout(5000);
    try {
      console.info("Sending message text to Host:", this.messageText());
      const { isError } = await appInstance.sendMessage(
        { role: "user", content: [{ type: "text", text: this.messageText() }] },
        { signal },
      );
      console.info("Message", isError ? "rejected" : "accepted");
    } catch (e) {
      console.error("Message send error:", signal.aborted ? "timed out" : e);
    }
  }

  async handleSendLog(): Promise<void> {
    const appInstance = this.app();
    if (!appInstance) return;

    console.info("Sending log text to Host:", this.logText());
    await appInstance.sendLog({ level: "info", data: this.logText() });
  }

  async handleOpenLink(): Promise<void> {
    const appInstance = this.app();
    if (!appInstance) return;

    console.info("Sending open link request to Host:", this.linkUrl());
    const { isError } = await appInstance.openLink({ url: this.linkUrl() });
    console.info("Open link request", isError ? "rejected" : "accepted");
  }
}

bootstrapApplication(GetTimeAppComponent, {
  providers: [provideZonelessChangeDetection()],
});
